# Generated by Django 4.0 on 2022-04-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Familia', models.CharField(blank=True, max_length=30)),
                ('Actividad', models.CharField(max_length=50)),
                ('Labor', models.CharField(max_length=50)),
                ('Modo', models.CharField(max_length=100)),
                ('OT', models.CharField(blank=True, max_length=20)),
                ('Ciclo', models.CharField(blank=True, max_length=20)),
                ('Item', models.CharField(max_length=100)),
                ('Finca', models.CharField(max_length=50)),
                ('Parcela', models.CharField(max_length=50)),
                ('IN_Uds', models.FloatField()),
                ('IN_CRC', models.FloatField()),
                ('MO_Hrs', models.FloatField()),
                ('MO_CRC', models.FloatField()),
                ('MAQ_Hrs', models.FloatField()),
                ('MAQ_CRC', models.FloatField()),
                ('Tot_CRC', models.FloatField()),
                ('Area', models.FloatField()),
                ('Diesel', models.FloatField()),
                ('Gas', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Database',
            },
        ),
        migrations.CreateModel(
            name='Geojson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Geojson',
            },
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finca', models.CharField(max_length=2)),
                ('parcela', models.CharField(max_length=30)),
                ('area', models.FloatField()),
                ('altitud', models.IntegerField(blank=True, null=True)),
                ('variedad', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclos', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Parcelas',
            },
        ),
        migrations.CreateModel(
            name='QB_Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=50)),
                ('payroll', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('item', models.CharField(blank=True, max_length=50)),
                ('lote', models.CharField(max_length=100)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'QB_Input',
            },
        ),
    ]
