# Generated by Django 4.0 on 2022-06-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='Cosecha',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
